registro/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url
from registro import views


urlpatterns = patterns('',
  url(r'^$', views.Consultar, name='consultar'),
  url(r'^registrar$', views.Registrar, name='registrar'),
  url(r'^editar/(?P<pk>\d+)$', views.Editar, name='editar'),
  url(r'^borrar/(?P<pk>\d+)$', views.Borrar, name='borrar'),
)

registro_vistas_funciones/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^', include('registro.urls', namespace='registro')),
]

registro/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.core.urlresolvers import reverse


class Persona(models.Model):
    nombre = models.CharField(max_length=200)
    cedula = models.CharField(max_length=8)

    def __unicode__(self):
        return self.nombre

    def get_absolute_url(self):
        return reverse('registro:editar', kwargs={'pk': self.pk})

registro/views.py
# -*- coding: utf-8 -*-from django.shortcuts import render, redirect, get_object_or_404
from django.forms import ModelForm
from django.http import HttpResponseRedirect
from django.shortcuts import redirect
from registro.models import Persona
from django.shortcuts import render
from django.shortcuts import get_object_or_404


class PersonaForm(ModelForm):
    class Meta:
        model = Persona
        fields = ['nombre', 'cedula']


def Consultar(request, template_name='registro/consultar.html'):
    persona = Persona.objects.all()
    data = {}
    data['object_list'] = persona
    return render(request, template_name, data)


def Registrar(request, template_name='registro/registrar.html'):
    form = PersonaForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect('registro:consultar')
    return render(request, template_name, {'form':form})


def Editar(request, pk, template_name='registro/registrar.html'):
    persona = get_object_or_404(Persona, pk=pk)
    form = PersonaForm(request.POST or None, instance=persona)
    if form.is_valid():
        form.save()
        return redirect('registro:consultar')
    return render(request, template_name, {'form':form})


def Borrar(request, pk, template_name='registro/borrar.html'):
    persona= get_object_or_404(Persona, pk=pk)    
    if request.method=='POST':
        persona.delete()
        return redirect('registro:consultar')
    return render(request, template_name, {'object':persona})

registro/templates/registro/borrar.html
<form method="post">{% csrf_token %}
    Are you sure you want to delete "{{ object }}" ?
    <input type="submit" value="Submit" />
</form>

registro/templates/registro/consultar.html
<h1>Personas</h1>
<ul>
    {% for persona in object_list %}
    <li>{{ persona.nombre }} {{ persona.cedula }}
    <a href="{% url 'registro:editar' persona.id %}">editar</a>
    <a href="{% url 'registro:borrar' persona.id %}">borrar</a>
    </li>
    {% endfor %}
</ul>

<a href="{% url 'registro:registrar' %}">Registrar</a>

registro/templates/registro/registrar.html
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit" />
</form>